tasks:
  - name: translate
    input:
      name: '@mark-magic/plugin-local'
      config:
        path: './docs/zh-CN'
    transforms:
      - name: '@mark-magic/plugin-doctran'
        config:
          engine: 'openai'
          to: 'en'
          apiKey: ${OPENAI_API_KEY}
          model: 'gpt-4o'
    output:
      name: '@mark-magic/plugin-local'
      config:
        path: './docs/en-US'
